---
- name: Playbook to configure hosts using plugins.
  hosts: R1
  gather_facts: no

  tasks:
  - name: Configuring IOSXR interface
    iosxr_l3_interfaces:
      config:
      - name: GigabitEthernet0/0/0/2
        ipv4:
        - address: 192.168.0.1/32
      state: replaced
    iosxr_interfaces:
      config:
      - name: GigabitEthernet0/0/0/2
        description: 'Configured using iosxr_interfaces'