---
- name: Create users on vyos network
  hosts: vyos_network
  vars_files:
  - ../vars/users-secret.yml

  tasks:
  - name: Looping..
    vyos_user:
      name: "{{ item.name }}"
      configured_password: "{{ item.password }}"
      state: present
    loop: "{{ newuser }}"
    loop_control:
      label: "{{ item.name }}"
