---
- name: Show interface check using with_dict function.
  # hosts: [ios_routers, iosxr_routers]
  hosts: ios_routers
  gather_facts: no

  vars_files:
    - "../vars/myvars.yml"
  
  tasks:
  - name: Checking show command
    ios_facts:
      gather_subset: all
    register: show_output
    #above output MUST have dictionary with keys and values to work. If a dictionary starts with list i.e. it does not have any key element, it will throw as error when using "with_dict" and "when" conditional variables.

  - name: Show command output
    debug:
      msg: "{{ show_output }}"
    with_dict: "{{ ansible_net_interfaces }}"
    when:
     - item.key == source_interface
     - item.value['operstatus'] == 'up'

  # - name: Show command output
  #   copy:
  #     dest: "{{ log_file }}"
  # #     # content: "{{ ping_output }}\n=== stderr: ======\n{{ ping_output.stderr }}"
  #     content: "{{ show_output[ansible_net_interfaces] }}"
  # #   #   content: "{{ show_output.results[0].stdout}}"
  #     with_dict: "{{ ansible_net_interfaces }}"
  #     # ###Specify predefined dictionary variable in below comment.
  #     when:
  #     - item.key == target_interface
  #     - item.value['operstatus'] == 'up'