---
- name: "IOS PING playbook with extra vars (-e) option specified in the bash command"
  hosts: [ios_routers,iosxr_routers]
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    #We can use this section to define variables which will be used by this playbook/plays below.

  tasks:

  - name: Check ping to "{{destination}}" from IOS Device
    #This task uses the destination value defined with variable -e in linux terminal while executing this playbook.
    ios_ping:
      dest: "{{destination}}"
    register: result
      
  - name: Printing ping response
    #This task is print the output collected in registered variable "data" which is present in above task.
    debug:
      msg: "{{result}}"