---
interfaces:
    Loopback0:
      intf_description: Routing Interface
      ipv4_addr: 34.0.0.2 255.255.255.255
      ipv6_addr: 2001:db8:34::2/64
      ipv6_addr_ll: 'fe80::2'
      ipv4: '34.0.0.2'
    Ethernet0/0:
      intf_description: Mgmt Interface
      ipv4_addr: 10.10.1.2 255.255.0.0
      ipv6_addr: 2001:db8:10:10:1::2/64
      ipv6_addr_ll: 'fe80::2'
    Ethernet0/1:
      intf_description: 'AS65535 Towards R1 Gi0/0/0/1'
      ipv4_addr: 12.34.35.2 255.255.255.0
      ipv6_addr: 2001:db8:12:34:35::2/112
      ipv6_addr_ll: 'fe80::2'
    Ethernet0/2:
      intf_description: 'AS65533 Towards R5 Eth0/2'
      ipv4_addr: 25.33.34.2 255.255.255.0
      ipv6_addr: 2001:db8:25:33:34::2/112
      ipv6_addr_ll: 'fe80::2'

protocols:
  #BGP host vars
  BGP:
    ASN: 65534
    local_ipv4_route: 34.0.0.2
    local_ipv6_route: 2001:db8:34::2/128
    global:
      addr_type:
      - ipv4
      - ipv6
    neighbors:
      R5:
        neighbor_type: EBGP
        neighbor_IP: 25.33.34.5
        neighbor_ASN: 65533
        neighbor_addr_type:
          ipv4:
            in_policy: ACL_PASS_v4
            out_policy: ACL_PASS_v4
          ipv6:
            in_policy: ACL_PASS_v6
            out_policy: ACL_PASS_v6
      R1:
        neighbor_type: EBGP
        neighbor_IP: 12.34.35.1
        neighbor_ASN: 65535
        neighbor_addr_type:
          ipv4:
            in_policy: ACL_PASS_v4
            out_policy: ACL_PASS_v4
          ipv6:
            in_policy: ACL_PASS_v6
            out_policy: ACL_PASS_v6