---
interfaces:
    MgmtEth0/0/CPU0/0:
      intf_description: Mgmt Interface
      ipv4_addr: 10.10.1.3/16
      ipv6_addr: 2001:db8:10:10:1::3/64
      ipv6_addr_ll: 'fe80::3'
    Loopback0:
      intf_description: Routing Interface
      ipv4: '33.0.0.3'
      ipv4_addr: 33.0.0.3/32
      ipv6_addr: 2001:db8:33::3/64
      ipv6_addr_ll: 'fe80::3'
    GigabitEthernet0/0/0/0:
      intf_description: 'AS65533 Towards R5 Eth0/3'
      ipv4_addr: 35.33.33.3/24
      ipv6_addr: 2001:db8:35:33:33::3/112
      ipv6_addr_ll: 'fe80::3'
    GigabitEthernet0/0/0/1:
      intf_description: 'AS65536 Towards R6 Eth0/1'
      ipv4_addr: 36.33.36.3/24
      ipv6_addr: 2001:db8:36:33:36::3/112
      ipv6_addr_ll: 'fe80::3'
    GigabitEthernet0/0/0/2:
      intf_description: 'AS65533 Towards R7 Eth0/3'
      ipv4_addr: 37.33.33.3/24
      ipv6_addr: 2001:db8:37:33:33::3/112
      ipv6_addr_ll: 'fe80::3'

protocols:
  BGP:
    ASN: 65533
    local_ipv4_route: 33.0.0.3/32
    local_ipv6_route: 2001:db8:33::3/128
    global:
      addr_type:
      - ipv4
      - ipv6
      - vpnv4
      - vpnv6
    neighbors:
      R5:
        neighbor_type: IBGP
        neighbor_IP: 33.0.0.5
        neighbor_addr_type:
          vpnv4:
            in_policy: PASS
            out_policy: PASS
          vpnv6:
            in_policy: PASS
            out_policy: PASS
      R7:
        neighbor_type: IBGP
        neighbor_IP: 33.0.0.7
        neighbor_addr_type:
          vpnv4:
            in_policy: PASS
            out_policy: PASS
          vpnv6:
            in_policy: PASS
            out_policy: PASS
      R8:
        neighbor_type: IBGP
        neighbor_IP: 33.0.0.8
        neighbor_addr_type:
          vpnv4:
            in_policy: PASS
            out_policy: PASS
          vpnv6:
            in_policy: PASS
            out_policy: PASS
  ISIS:
    process_name: CORE65533
    process_type: level-2-only
    process_net_addr: '49.0001.3300.0003.00'
    global:
      addr_type:
      - ipv4
      - ipv6
      interfaces:
      - Loopback0
      - GigabitEthernet0/0/0/0
      - GigabitEthernet0/0/0/2
      # R6:
      #   neighbor_type: EBGP
      #   neighbor_IP: 18.33.35.8
      #   neighbor_ASN: 65533
      #   neighbor_addr_type:
      #     ipv4:
      #       in_policy: PASS
      #       out_policy: PASS
      #     ipv6:
      #       in_policy: PASS
      #       out_policy: PASS
